package_assets:         on          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
#package_path:           packages    # (defaults to assets)
javascript_compressor:  yui     # (yui, closure)
allow_debugging:        on
# compressor_options:
#   compilation_level: ADVANCED_OPTIMIZATIONS
  
javascripts:
  workspace:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/lib/*.js
    - public/javascripts/views/**/*.js
    # - app/views/workspace/*.jst

stylesheets:
  common:
    # - public/stylesheets/reset.css
    - public/stylesheets/*.css
  workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css